<a href="https://colab.research.google.com/github/afraz-rupak/Building-Your-First-ANN-with-TensorFlow/blob/main/Building_Your_First_ANN_with_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Data Preprocessing
- Add input layer
- Random w init
- Add Hidden Layers
- Select Optimizer, Loss, and Performance Metrics
- Compile the model
- use model.fit to train the model
- Evaluate the model
- Adjust optimization parameters or model if needed

In [55]:
# pip install tensorflow==2.0.0-rc0
# pip install tensorflow-gpu==2.0.0-rc0

In [56]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense, Dropout
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report
tf.random.set_seed(0)

In [57]:
print(tf.__version__)

2.8.0


In [58]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [59]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [60]:
file_path='/content/drive/MyDrive/Building-Your-First-ANN-with-TensorFlow/Customer_Churn_Modelling.csv'

In [61]:
dataset = pd.read_csv(file_path)

In [62]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [63]:
X = dataset.drop(labels=['CustomerId', 'Surname', 'RowNumber', 'Exited'], axis = 1)
y = dataset['Exited']

In [64]:
X.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [65]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [66]:
from sklearn.preprocessing import LabelEncoder

In [67]:
label1 = LabelEncoder()
X['Geography'] = label1.fit_transform(X['Geography'])

In [68]:
X.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0  Female   42       2       0.00              1   
1          608          2  Female   41       1   83807.86              1   
2          502          0  Female   42       8  159660.80              3   
3          699          0  Female   39       1       0.00              2   
4          850          2  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [69]:
label = LabelEncoder()
X['Gender'] = label.fit_transform(X['Gender'])
X.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [70]:
X = pd.get_dummies(X, drop_first=True, columns=['Geography'])
X.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_1  Geography_2  
0               1        101348.88            0            0  
1               1        112542.58            0            1  
2               0        113931.57            0            0  
3               0         93826.63            0            0  
4               1         79084.10            0            1

### Feature Standardization 

In [71]:
from sklearn.preprocessing import StandardScaler

In [72]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0, stratify = y)

In [73]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [74]:
X_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

### Build ANN 

In [75]:
model = Sequential()
model.add(Dense(X.shape[1], activation='relu', input_dim = X.shape[1]))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation = 'sigmoid'))

In [76]:
X.shape[1]

11

In [77]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [78]:
model.fit(X_train, y_train.to_numpy(), batch_size = 10, epochs = 10, verbose = 1)

Epoch 1/10
800/800 [==============================] - 2s 2ms/step - loss: 0.4599 - accuracy: 0.8029
Epoch 2/10
800/800 [==============================] - 2s 2ms/step - loss: 0.4094 - accuracy: 0.8286
Epoch 3/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3702 - accuracy: 0.8479
Epoch 4/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3555 - accuracy: 0.8545
Epoch 5/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3478 - accuracy: 0.8560
Epoch 6/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3459 - accuracy: 0.8546
Epoch 7/10
800/800 [==============================] - 2s 2ms/step - loss: 0.3418 - accuracy: 0.8550
Epoch 8/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3394 - accuracy: 0.8571
Epoch 9/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3375 - accuracy: 0.8576
Epoch 10/10
800/800 [==============================] - 1s 2ms/step - loss: 0.3346 - accuracy: 0.8608

In [79]:
y_pred = model.predict(X_test)

In [80]:
y_pred

array([[0.13397175],
       [0.1711987 ],
       [0.08210427],
       ...,
       [0.0206053 ],
       [0.99993014],
       [0.09724927]], dtype=float32)

In [81]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [82]:
model.evaluate(X_test, y_test.to_numpy())

63/63 [==============================] - 0s 2ms/step - loss: 0.3535 - accuracy: 0.8495


[0.35345298051834106, 0.8495000004768372]

In [83]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [89]:
confusion_matrix(y_test, y_pred.round())

array([[1503,   90],
       [ 211,  196]])

In [87]:
accuracy_score(y_test, y_pred.round(), normalize=False)

1699